// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("libvirt");

/**
 * libvirt connection URI for operations. See https://libvirt.org/uri.html
 */
export declare const uri: string | undefined;
Object.defineProperty(exports, "uri", {
    get() {
        return __config.get("uri");
    },
    enumerable: true,
});

