keys:
  - &hades age1p0uw4hxuhrnf93tz62rntvquqrgxdzj8scykf5xu5dhfeuptv3dq6zd39a
  - &darter age1uezgu6hzmnzspf446havmdz682gw9wm273tn0w9m82qxm63pfqlqxfyys0
  - &gaea age1j7vr2z2xhhelnpljrcs8r34hjwpsnd9hmqq25hr2ynegrq8ehudsa4kf67
  - &zeus age124unzmrq8de2qh9a9z7u96dm258w3y7ytumswx344wf980uwpfmqvuc775
  - &pik8s1 age16c82v4dsh2emnrrl64ya9mx2kscj7t440gslttgnnrvvj9zvketssjwynx
  - &pik8s2 age13g94d3h44frn6axrgz6u6gw5kmvzr3a4ytp4l7qnrv3rtre2cvuqu9musf
  - &pik8s3 age1rnuup00fn4w0h30a4ffv6m9ayg0shgqrfm0xhxw7txlpegy9736sjjx9ul
  - &pik8s5 age1dskgmw3psffk5eyxzz0a3jtvars54pdzyue62xgm9qv2u8tpm47q9fkcaz
  - &pik8s6 age1re9qdeg4p2s9wxyj65f3e4y7uvfmpenzzfkh2h0cjh98lqugg5zqk95zsp

creation_rules:
  - path_regex: hosts/hades/secrets/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *hades
  - path_regex: hosts/darter/secrets/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *darter
  - path_regex: hosts/gaea/secrets/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *gaea
  - path_regex: hosts/zeus/secrets/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *zeus
  - path_regex: secrets/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *hades
          - *darter
          - *gaea
          - *zeus
          - *pik8s1
          - *pik8s2
          - *pik8s3
          - *pik8s5
          - *pik8s6
