// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CloudinitDisk extends pulumi.CustomResource {
    /**
     * Get an existing CloudinitDisk resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CloudinitDiskState, opts?: pulumi.CustomResourceOptions): CloudinitDisk {
        return new CloudinitDisk(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'libvirt:index/cloudinitDisk:CloudinitDisk';

    /**
     * Returns true if the given object is an instance of CloudinitDisk.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CloudinitDisk {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudinitDisk.__pulumiType;
    }

    public readonly cloudinitDiskId!: pulumi.Output<string>;
    public readonly metaData!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly networkConfig!: pulumi.Output<string | undefined>;
    public readonly pool!: pulumi.Output<string | undefined>;
    public readonly userData!: pulumi.Output<string | undefined>;

    /**
     * Create a CloudinitDisk resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CloudinitDiskArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CloudinitDiskArgs | CloudinitDiskState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CloudinitDiskState | undefined;
            resourceInputs["cloudinitDiskId"] = state ? state.cloudinitDiskId : undefined;
            resourceInputs["metaData"] = state ? state.metaData : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["networkConfig"] = state ? state.networkConfig : undefined;
            resourceInputs["pool"] = state ? state.pool : undefined;
            resourceInputs["userData"] = state ? state.userData : undefined;
        } else {
            const args = argsOrState as CloudinitDiskArgs | undefined;
            resourceInputs["cloudinitDiskId"] = args ? args.cloudinitDiskId : undefined;
            resourceInputs["metaData"] = args ? args.metaData : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkConfig"] = args ? args.networkConfig : undefined;
            resourceInputs["pool"] = args ? args.pool : undefined;
            resourceInputs["userData"] = args ? args.userData : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CloudinitDisk.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CloudinitDisk resources.
 */
export interface CloudinitDiskState {
    cloudinitDiskId?: pulumi.Input<string>;
    metaData?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    networkConfig?: pulumi.Input<string>;
    pool?: pulumi.Input<string>;
    userData?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CloudinitDisk resource.
 */
export interface CloudinitDiskArgs {
    cloudinitDiskId?: pulumi.Input<string>;
    metaData?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    networkConfig?: pulumi.Input<string>;
    pool?: pulumi.Input<string>;
    userData?: pulumi.Input<string>;
}
