// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainState, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'libvirt:index/domain:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    public readonly arch!: pulumi.Output<string>;
    public readonly autostart!: pulumi.Output<boolean>;
    public readonly bootDevices!: pulumi.Output<outputs.DomainBootDevice[] | undefined>;
    public readonly cloudinit!: pulumi.Output<string | undefined>;
    public readonly cmdlines!: pulumi.Output<{[key: string]: string}[] | undefined>;
    public readonly consoles!: pulumi.Output<outputs.DomainConsole[] | undefined>;
    public readonly coreosIgnition!: pulumi.Output<string | undefined>;
    public readonly cpu!: pulumi.Output<outputs.DomainCpu | undefined>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly disks!: pulumi.Output<outputs.DomainDisk[] | undefined>;
    public readonly domainId!: pulumi.Output<string>;
    public readonly emulator!: pulumi.Output<string>;
    public readonly filesystems!: pulumi.Output<outputs.DomainFilesystem[] | undefined>;
    public readonly firmware!: pulumi.Output<string | undefined>;
    public readonly fwCfgName!: pulumi.Output<string | undefined>;
    public readonly graphics!: pulumi.Output<outputs.DomainGraphics | undefined>;
    public readonly initrd!: pulumi.Output<string | undefined>;
    public readonly kernel!: pulumi.Output<string | undefined>;
    public readonly machine!: pulumi.Output<string>;
    public readonly memory!: pulumi.Output<number | undefined>;
    public readonly metadata!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly networkInterfaces!: pulumi.Output<outputs.DomainNetworkInterface[] | undefined>;
    public readonly nvram!: pulumi.Output<outputs.DomainNvram | undefined>;
    public readonly qemuAgent!: pulumi.Output<boolean | undefined>;
    public readonly running!: pulumi.Output<boolean | undefined>;
    public readonly timeouts!: pulumi.Output<outputs.DomainTimeouts | undefined>;
    public readonly tpm!: pulumi.Output<outputs.DomainTpm | undefined>;
    public readonly type!: pulumi.Output<string | undefined>;
    public readonly vcpu!: pulumi.Output<number | undefined>;
    public readonly video!: pulumi.Output<outputs.DomainVideo | undefined>;
    public readonly xml!: pulumi.Output<outputs.DomainXml | undefined>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainArgs | DomainState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DomainState | undefined;
            resourceInputs["arch"] = state ? state.arch : undefined;
            resourceInputs["autostart"] = state ? state.autostart : undefined;
            resourceInputs["bootDevices"] = state ? state.bootDevices : undefined;
            resourceInputs["cloudinit"] = state ? state.cloudinit : undefined;
            resourceInputs["cmdlines"] = state ? state.cmdlines : undefined;
            resourceInputs["consoles"] = state ? state.consoles : undefined;
            resourceInputs["coreosIgnition"] = state ? state.coreosIgnition : undefined;
            resourceInputs["cpu"] = state ? state.cpu : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["disks"] = state ? state.disks : undefined;
            resourceInputs["domainId"] = state ? state.domainId : undefined;
            resourceInputs["emulator"] = state ? state.emulator : undefined;
            resourceInputs["filesystems"] = state ? state.filesystems : undefined;
            resourceInputs["firmware"] = state ? state.firmware : undefined;
            resourceInputs["fwCfgName"] = state ? state.fwCfgName : undefined;
            resourceInputs["graphics"] = state ? state.graphics : undefined;
            resourceInputs["initrd"] = state ? state.initrd : undefined;
            resourceInputs["kernel"] = state ? state.kernel : undefined;
            resourceInputs["machine"] = state ? state.machine : undefined;
            resourceInputs["memory"] = state ? state.memory : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["networkInterfaces"] = state ? state.networkInterfaces : undefined;
            resourceInputs["nvram"] = state ? state.nvram : undefined;
            resourceInputs["qemuAgent"] = state ? state.qemuAgent : undefined;
            resourceInputs["running"] = state ? state.running : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["tpm"] = state ? state.tpm : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
            resourceInputs["vcpu"] = state ? state.vcpu : undefined;
            resourceInputs["video"] = state ? state.video : undefined;
            resourceInputs["xml"] = state ? state.xml : undefined;
        } else {
            const args = argsOrState as DomainArgs | undefined;
            resourceInputs["arch"] = args ? args.arch : undefined;
            resourceInputs["autostart"] = args ? args.autostart : undefined;
            resourceInputs["bootDevices"] = args ? args.bootDevices : undefined;
            resourceInputs["cloudinit"] = args ? args.cloudinit : undefined;
            resourceInputs["cmdlines"] = args ? args.cmdlines : undefined;
            resourceInputs["consoles"] = args ? args.consoles : undefined;
            resourceInputs["coreosIgnition"] = args ? args.coreosIgnition : undefined;
            resourceInputs["cpu"] = args ? args.cpu : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["disks"] = args ? args.disks : undefined;
            resourceInputs["domainId"] = args ? args.domainId : undefined;
            resourceInputs["emulator"] = args ? args.emulator : undefined;
            resourceInputs["filesystems"] = args ? args.filesystems : undefined;
            resourceInputs["firmware"] = args ? args.firmware : undefined;
            resourceInputs["fwCfgName"] = args ? args.fwCfgName : undefined;
            resourceInputs["graphics"] = args ? args.graphics : undefined;
            resourceInputs["initrd"] = args ? args.initrd : undefined;
            resourceInputs["kernel"] = args ? args.kernel : undefined;
            resourceInputs["machine"] = args ? args.machine : undefined;
            resourceInputs["memory"] = args ? args.memory : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkInterfaces"] = args ? args.networkInterfaces : undefined;
            resourceInputs["nvram"] = args ? args.nvram : undefined;
            resourceInputs["qemuAgent"] = args ? args.qemuAgent : undefined;
            resourceInputs["running"] = args ? args.running : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["tpm"] = args ? args.tpm : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["vcpu"] = args ? args.vcpu : undefined;
            resourceInputs["video"] = args ? args.video : undefined;
            resourceInputs["xml"] = args ? args.xml : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Domain.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Domain resources.
 */
export interface DomainState {
    arch?: pulumi.Input<string>;
    autostart?: pulumi.Input<boolean>;
    bootDevices?: pulumi.Input<pulumi.Input<inputs.DomainBootDevice>[]>;
    cloudinit?: pulumi.Input<string>;
    cmdlines?: pulumi.Input<pulumi.Input<{[key: string]: pulumi.Input<string>}>[]>;
    consoles?: pulumi.Input<pulumi.Input<inputs.DomainConsole>[]>;
    coreosIgnition?: pulumi.Input<string>;
    cpu?: pulumi.Input<inputs.DomainCpu>;
    description?: pulumi.Input<string>;
    disks?: pulumi.Input<pulumi.Input<inputs.DomainDisk>[]>;
    domainId?: pulumi.Input<string>;
    emulator?: pulumi.Input<string>;
    filesystems?: pulumi.Input<pulumi.Input<inputs.DomainFilesystem>[]>;
    firmware?: pulumi.Input<string>;
    fwCfgName?: pulumi.Input<string>;
    graphics?: pulumi.Input<inputs.DomainGraphics>;
    initrd?: pulumi.Input<string>;
    kernel?: pulumi.Input<string>;
    machine?: pulumi.Input<string>;
    memory?: pulumi.Input<number>;
    metadata?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    networkInterfaces?: pulumi.Input<pulumi.Input<inputs.DomainNetworkInterface>[]>;
    nvram?: pulumi.Input<inputs.DomainNvram>;
    qemuAgent?: pulumi.Input<boolean>;
    running?: pulumi.Input<boolean>;
    timeouts?: pulumi.Input<inputs.DomainTimeouts>;
    tpm?: pulumi.Input<inputs.DomainTpm>;
    type?: pulumi.Input<string>;
    vcpu?: pulumi.Input<number>;
    video?: pulumi.Input<inputs.DomainVideo>;
    xml?: pulumi.Input<inputs.DomainXml>;
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    arch?: pulumi.Input<string>;
    autostart?: pulumi.Input<boolean>;
    bootDevices?: pulumi.Input<pulumi.Input<inputs.DomainBootDevice>[]>;
    cloudinit?: pulumi.Input<string>;
    cmdlines?: pulumi.Input<pulumi.Input<{[key: string]: pulumi.Input<string>}>[]>;
    consoles?: pulumi.Input<pulumi.Input<inputs.DomainConsole>[]>;
    coreosIgnition?: pulumi.Input<string>;
    cpu?: pulumi.Input<inputs.DomainCpu>;
    description?: pulumi.Input<string>;
    disks?: pulumi.Input<pulumi.Input<inputs.DomainDisk>[]>;
    domainId?: pulumi.Input<string>;
    emulator?: pulumi.Input<string>;
    filesystems?: pulumi.Input<pulumi.Input<inputs.DomainFilesystem>[]>;
    firmware?: pulumi.Input<string>;
    fwCfgName?: pulumi.Input<string>;
    graphics?: pulumi.Input<inputs.DomainGraphics>;
    initrd?: pulumi.Input<string>;
    kernel?: pulumi.Input<string>;
    machine?: pulumi.Input<string>;
    memory?: pulumi.Input<number>;
    metadata?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    networkInterfaces?: pulumi.Input<pulumi.Input<inputs.DomainNetworkInterface>[]>;
    nvram?: pulumi.Input<inputs.DomainNvram>;
    qemuAgent?: pulumi.Input<boolean>;
    running?: pulumi.Input<boolean>;
    timeouts?: pulumi.Input<inputs.DomainTimeouts>;
    tpm?: pulumi.Input<inputs.DomainTpm>;
    type?: pulumi.Input<string>;
    vcpu?: pulumi.Input<number>;
    video?: pulumi.Input<inputs.DomainVideo>;
    xml?: pulumi.Input<inputs.DomainXml>;
}
