// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNetworkDnsmasqOptionsTemplate(args: GetNetworkDnsmasqOptionsTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkDnsmasqOptionsTemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("libvirt:index/getNetworkDnsmasqOptionsTemplate:getNetworkDnsmasqOptionsTemplate", {
        "id": args.id,
        "optionName": args.optionName,
        "optionValue": args.optionValue,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkDnsmasqOptionsTemplate.
 */
export interface GetNetworkDnsmasqOptionsTemplateArgs {
    id?: string;
    optionName: string;
    optionValue?: string;
}

/**
 * A collection of values returned by getNetworkDnsmasqOptionsTemplate.
 */
export interface GetNetworkDnsmasqOptionsTemplateResult {
    readonly id: string;
    readonly optionName: string;
    readonly optionValue?: string;
    readonly rendered: {[key: string]: string};
}
export function getNetworkDnsmasqOptionsTemplateOutput(args: GetNetworkDnsmasqOptionsTemplateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNetworkDnsmasqOptionsTemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("libvirt:index/getNetworkDnsmasqOptionsTemplate:getNetworkDnsmasqOptionsTemplate", {
        "id": args.id,
        "optionName": args.optionName,
        "optionValue": args.optionValue,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkDnsmasqOptionsTemplate.
 */
export interface GetNetworkDnsmasqOptionsTemplateOutputArgs {
    id?: pulumi.Input<string>;
    optionName: pulumi.Input<string>;
    optionValue?: pulumi.Input<string>;
}
