// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNodeInfo(args?: GetNodeInfoArgs, opts?: pulumi.InvokeOptions): Promise<GetNodeInfoResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("libvirt:index/getNodeInfo:getNodeInfo", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNodeInfo.
 */
export interface GetNodeInfoArgs {
    id?: string;
}

/**
 * A collection of values returned by getNodeInfo.
 */
export interface GetNodeInfoResult {
    readonly cpuCoresPerSocket: number;
    readonly cpuCoresTotal: number;
    readonly cpuModel: string;
    readonly cpuSockets: number;
    readonly cpuThreadsPerCore: number;
    readonly id: string;
    readonly memoryTotalKb: number;
    readonly numaNodes: number;
}
export function getNodeInfoOutput(args?: GetNodeInfoOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNodeInfoResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("libvirt:index/getNodeInfo:getNodeInfo", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNodeInfo.
 */
export interface GetNodeInfoOutputArgs {
    id?: pulumi.Input<string>;
}
