// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNetworkDnsHostTemplate(args: GetNetworkDnsHostTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkDnsHostTemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("libvirt:index/getNetworkDnsHostTemplate:getNetworkDnsHostTemplate", {
        "hostname": args.hostname,
        "id": args.id,
        "ip": args.ip,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkDnsHostTemplate.
 */
export interface GetNetworkDnsHostTemplateArgs {
    hostname: string;
    id?: string;
    ip: string;
}

/**
 * A collection of values returned by getNetworkDnsHostTemplate.
 */
export interface GetNetworkDnsHostTemplateResult {
    readonly hostname: string;
    readonly id: string;
    readonly ip: string;
    readonly rendered: {[key: string]: string};
}
export function getNetworkDnsHostTemplateOutput(args: GetNetworkDnsHostTemplateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNetworkDnsHostTemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("libvirt:index/getNetworkDnsHostTemplate:getNetworkDnsHostTemplate", {
        "hostname": args.hostname,
        "id": args.id,
        "ip": args.ip,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkDnsHostTemplate.
 */
export interface GetNetworkDnsHostTemplateOutputArgs {
    hostname: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    ip: pulumi.Input<string>;
}
