// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNodeDevices(args?: GetNodeDevicesArgs, opts?: pulumi.InvokeOptions): Promise<GetNodeDevicesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("libvirt:index/getNodeDevices:getNodeDevices", {
        "capability": args.capability,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNodeDevices.
 */
export interface GetNodeDevicesArgs {
    capability?: string;
    id?: string;
}

/**
 * A collection of values returned by getNodeDevices.
 */
export interface GetNodeDevicesResult {
    readonly capability?: string;
    readonly devices: string[];
    readonly id: string;
}
export function getNodeDevicesOutput(args?: GetNodeDevicesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNodeDevicesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("libvirt:index/getNodeDevices:getNodeDevices", {
        "capability": args.capability,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNodeDevices.
 */
export interface GetNodeDevicesOutputArgs {
    capability?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
}
