// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNodeDeviceInfo(args: GetNodeDeviceInfoArgs, opts?: pulumi.InvokeOptions): Promise<GetNodeDeviceInfoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("libvirt:index/getNodeDeviceInfo:getNodeDeviceInfo", {
        "capability": args.capability,
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNodeDeviceInfo.
 */
export interface GetNodeDeviceInfoArgs {
    capability?: inputs.GetNodeDeviceInfoCapability;
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getNodeDeviceInfo.
 */
export interface GetNodeDeviceInfoResult {
    readonly capability?: outputs.GetNodeDeviceInfoCapability;
    readonly devnodes: outputs.GetNodeDeviceInfoDevnode[];
    readonly id: string;
    readonly name: string;
    readonly parent: string;
    readonly path: string;
    readonly xml: string;
}
export function getNodeDeviceInfoOutput(args: GetNodeDeviceInfoOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNodeDeviceInfoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("libvirt:index/getNodeDeviceInfo:getNodeDeviceInfo", {
        "capability": args.capability,
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNodeDeviceInfo.
 */
export interface GetNodeDeviceInfoOutputArgs {
    capability?: pulumi.Input<inputs.GetNodeDeviceInfoCapabilityArgs>;
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
