// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Network extends pulumi.CustomResource {
    /**
     * Get an existing Network resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkState, opts?: pulumi.CustomResourceOptions): Network {
        return new Network(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'libvirt:index/network:Network';

    /**
     * Returns true if the given object is an instance of Network.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Network {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Network.__pulumiType;
    }

    public readonly addresses!: pulumi.Output<string[] | undefined>;
    public readonly autostart!: pulumi.Output<boolean>;
    public readonly bridge!: pulumi.Output<string>;
    public readonly dhcp!: pulumi.Output<outputs.NetworkDhcp | undefined>;
    public readonly dns!: pulumi.Output<outputs.NetworkDns | undefined>;
    public readonly dnsmasqOptions!: pulumi.Output<outputs.NetworkDnsmasqOptions | undefined>;
    public readonly domain!: pulumi.Output<string | undefined>;
    public readonly mode!: pulumi.Output<string | undefined>;
    public readonly mtu!: pulumi.Output<number | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly networkId!: pulumi.Output<string>;
    public readonly routes!: pulumi.Output<outputs.NetworkRoute[] | undefined>;
    public readonly xml!: pulumi.Output<outputs.NetworkXml | undefined>;

    /**
     * Create a Network resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NetworkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkArgs | NetworkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkState | undefined;
            resourceInputs["addresses"] = state ? state.addresses : undefined;
            resourceInputs["autostart"] = state ? state.autostart : undefined;
            resourceInputs["bridge"] = state ? state.bridge : undefined;
            resourceInputs["dhcp"] = state ? state.dhcp : undefined;
            resourceInputs["dns"] = state ? state.dns : undefined;
            resourceInputs["dnsmasqOptions"] = state ? state.dnsmasqOptions : undefined;
            resourceInputs["domain"] = state ? state.domain : undefined;
            resourceInputs["mode"] = state ? state.mode : undefined;
            resourceInputs["mtu"] = state ? state.mtu : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["networkId"] = state ? state.networkId : undefined;
            resourceInputs["routes"] = state ? state.routes : undefined;
            resourceInputs["xml"] = state ? state.xml : undefined;
        } else {
            const args = argsOrState as NetworkArgs | undefined;
            resourceInputs["addresses"] = args ? args.addresses : undefined;
            resourceInputs["autostart"] = args ? args.autostart : undefined;
            resourceInputs["bridge"] = args ? args.bridge : undefined;
            resourceInputs["dhcp"] = args ? args.dhcp : undefined;
            resourceInputs["dns"] = args ? args.dns : undefined;
            resourceInputs["dnsmasqOptions"] = args ? args.dnsmasqOptions : undefined;
            resourceInputs["domain"] = args ? args.domain : undefined;
            resourceInputs["mode"] = args ? args.mode : undefined;
            resourceInputs["mtu"] = args ? args.mtu : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkId"] = args ? args.networkId : undefined;
            resourceInputs["routes"] = args ? args.routes : undefined;
            resourceInputs["xml"] = args ? args.xml : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Network.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Network resources.
 */
export interface NetworkState {
    addresses?: pulumi.Input<pulumi.Input<string>[]>;
    autostart?: pulumi.Input<boolean>;
    bridge?: pulumi.Input<string>;
    dhcp?: pulumi.Input<inputs.NetworkDhcp>;
    dns?: pulumi.Input<inputs.NetworkDns>;
    dnsmasqOptions?: pulumi.Input<inputs.NetworkDnsmasqOptions>;
    domain?: pulumi.Input<string>;
    mode?: pulumi.Input<string>;
    mtu?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    networkId?: pulumi.Input<string>;
    routes?: pulumi.Input<pulumi.Input<inputs.NetworkRoute>[]>;
    xml?: pulumi.Input<inputs.NetworkXml>;
}

/**
 * The set of arguments for constructing a Network resource.
 */
export interface NetworkArgs {
    addresses?: pulumi.Input<pulumi.Input<string>[]>;
    autostart?: pulumi.Input<boolean>;
    bridge?: pulumi.Input<string>;
    dhcp?: pulumi.Input<inputs.NetworkDhcp>;
    dns?: pulumi.Input<inputs.NetworkDns>;
    dnsmasqOptions?: pulumi.Input<inputs.NetworkDnsmasqOptions>;
    domain?: pulumi.Input<string>;
    mode?: pulumi.Input<string>;
    mtu?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    networkId?: pulumi.Input<string>;
    routes?: pulumi.Input<pulumi.Input<inputs.NetworkRoute>[]>;
    xml?: pulumi.Input<inputs.NetworkXml>;
}
