// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Volume extends pulumi.CustomResource {
    /**
     * Get an existing Volume resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VolumeState, opts?: pulumi.CustomResourceOptions): Volume {
        return new Volume(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'libvirt:index/volume:Volume';

    /**
     * Returns true if the given object is an instance of Volume.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Volume {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Volume.__pulumiType;
    }

    public readonly baseVolumeId!: pulumi.Output<string | undefined>;
    public readonly baseVolumeName!: pulumi.Output<string | undefined>;
    public readonly baseVolumePool!: pulumi.Output<string | undefined>;
    public readonly format!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;
    public readonly pool!: pulumi.Output<string | undefined>;
    public readonly size!: pulumi.Output<number>;
    public readonly source!: pulumi.Output<string | undefined>;
    public readonly volumeId!: pulumi.Output<string>;
    public readonly xml!: pulumi.Output<outputs.VolumeXml | undefined>;

    /**
     * Create a Volume resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: VolumeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VolumeArgs | VolumeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VolumeState | undefined;
            resourceInputs["baseVolumeId"] = state ? state.baseVolumeId : undefined;
            resourceInputs["baseVolumeName"] = state ? state.baseVolumeName : undefined;
            resourceInputs["baseVolumePool"] = state ? state.baseVolumePool : undefined;
            resourceInputs["format"] = state ? state.format : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["pool"] = state ? state.pool : undefined;
            resourceInputs["size"] = state ? state.size : undefined;
            resourceInputs["source"] = state ? state.source : undefined;
            resourceInputs["volumeId"] = state ? state.volumeId : undefined;
            resourceInputs["xml"] = state ? state.xml : undefined;
        } else {
            const args = argsOrState as VolumeArgs | undefined;
            resourceInputs["baseVolumeId"] = args ? args.baseVolumeId : undefined;
            resourceInputs["baseVolumeName"] = args ? args.baseVolumeName : undefined;
            resourceInputs["baseVolumePool"] = args ? args.baseVolumePool : undefined;
            resourceInputs["format"] = args ? args.format : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["pool"] = args ? args.pool : undefined;
            resourceInputs["size"] = args ? args.size : undefined;
            resourceInputs["source"] = args ? args.source : undefined;
            resourceInputs["volumeId"] = args ? args.volumeId : undefined;
            resourceInputs["xml"] = args ? args.xml : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Volume.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Volume resources.
 */
export interface VolumeState {
    baseVolumeId?: pulumi.Input<string>;
    baseVolumeName?: pulumi.Input<string>;
    baseVolumePool?: pulumi.Input<string>;
    format?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    pool?: pulumi.Input<string>;
    size?: pulumi.Input<number>;
    source?: pulumi.Input<string>;
    volumeId?: pulumi.Input<string>;
    xml?: pulumi.Input<inputs.VolumeXml>;
}

/**
 * The set of arguments for constructing a Volume resource.
 */
export interface VolumeArgs {
    baseVolumeId?: pulumi.Input<string>;
    baseVolumeName?: pulumi.Input<string>;
    baseVolumePool?: pulumi.Input<string>;
    format?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    pool?: pulumi.Input<string>;
    size?: pulumi.Input<number>;
    source?: pulumi.Input<string>;
    volumeId?: pulumi.Input<string>;
    xml?: pulumi.Input<inputs.VolumeXml>;
}
