// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DomainBootDevice {
    devs?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface DomainConsole {
    sourceHost?: pulumi.Input<string>;
    sourcePath?: pulumi.Input<string>;
    sourceService?: pulumi.Input<string>;
    targetPort: pulumi.Input<string>;
    targetType?: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface DomainCpu {
    mode?: pulumi.Input<string>;
}

export interface DomainDisk {
    blockDevice?: pulumi.Input<string>;
    file?: pulumi.Input<string>;
    scsi?: pulumi.Input<boolean>;
    url?: pulumi.Input<string>;
    volumeId?: pulumi.Input<string>;
    wwn?: pulumi.Input<string>;
}

export interface DomainFilesystem {
    accessmode?: pulumi.Input<string>;
    readonly?: pulumi.Input<boolean>;
    source: pulumi.Input<string>;
    target: pulumi.Input<string>;
}

export interface DomainGraphics {
    autoport?: pulumi.Input<boolean>;
    listenAddress?: pulumi.Input<string>;
    listenType?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    websocket?: pulumi.Input<number>;
}

export interface DomainNetworkInterface {
    addresses?: pulumi.Input<pulumi.Input<string>[]>;
    bridge?: pulumi.Input<string>;
    hostname?: pulumi.Input<string>;
    mac?: pulumi.Input<string>;
    macvtap?: pulumi.Input<string>;
    networkId?: pulumi.Input<string>;
    networkName?: pulumi.Input<string>;
    passthrough?: pulumi.Input<string>;
    private?: pulumi.Input<string>;
    vepa?: pulumi.Input<string>;
    waitForLease?: pulumi.Input<boolean>;
}

export interface DomainNvram {
    file?: pulumi.Input<string>;
    template?: pulumi.Input<string>;
}

export interface DomainTimeouts {
    create?: pulumi.Input<string>;
}

export interface DomainTpm {
    backendDevicePath?: pulumi.Input<string>;
    backendEncryptionSecret?: pulumi.Input<string>;
    backendPersistentState?: pulumi.Input<boolean>;
    backendType?: pulumi.Input<string>;
    backendVersion?: pulumi.Input<string>;
    model?: pulumi.Input<string>;
}

export interface DomainVideo {
    type?: pulumi.Input<string>;
}

export interface DomainXml {
    xslt?: pulumi.Input<string>;
}

export interface GetNodeDeviceInfoCapability {
    address?: string;
    block?: string;
    bus?: string;
    capability?: {[key: string]: string};
    class?: string;
    description?: string;
    device?: string;
    domain?: string;
    driveType?: string;
    drmType?: string;
    features?: string[];
    firmware?: {[key: string]: string};
    function?: string;
    hardware?: {[key: string]: string};
    host?: string;
    interface?: string;
    iommuGroup?: inputs.GetNodeDeviceInfoCapabilityIommuGroup;
    link?: {[key: string]: string};
    logicalBlockSize?: string;
    lun?: string;
    model?: string;
    numBlocks?: string;
    number?: string;
    product?: {[key: string]: string};
    protocol?: string;
    scsiType?: string;
    serial?: string;
    size?: string;
    slot?: string;
    subclass?: string;
    target?: string;
    type?: string;
    uniqueId?: string;
    vendor?: {[key: string]: string};
}

export interface GetNodeDeviceInfoCapabilityArgs {
    address?: pulumi.Input<string>;
    block?: pulumi.Input<string>;
    bus?: pulumi.Input<string>;
    capability?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    class?: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    device?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
    driveType?: pulumi.Input<string>;
    drmType?: pulumi.Input<string>;
    features?: pulumi.Input<pulumi.Input<string>[]>;
    firmware?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    function?: pulumi.Input<string>;
    hardware?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    host?: pulumi.Input<string>;
    interface?: pulumi.Input<string>;
    iommuGroup?: pulumi.Input<inputs.GetNodeDeviceInfoCapabilityIommuGroupArgs>;
    link?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    logicalBlockSize?: pulumi.Input<string>;
    lun?: pulumi.Input<string>;
    model?: pulumi.Input<string>;
    numBlocks?: pulumi.Input<string>;
    number?: pulumi.Input<string>;
    product?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    protocol?: pulumi.Input<string>;
    scsiType?: pulumi.Input<string>;
    serial?: pulumi.Input<string>;
    size?: pulumi.Input<string>;
    slot?: pulumi.Input<string>;
    subclass?: pulumi.Input<string>;
    target?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    uniqueId?: pulumi.Input<string>;
    vendor?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

export interface GetNodeDeviceInfoCapabilityIommuGroup {
    addresses?: {[key: string]: string}[];
    number?: string;
}

export interface GetNodeDeviceInfoCapabilityIommuGroupArgs {
    addresses?: pulumi.Input<pulumi.Input<{[key: string]: pulumi.Input<string>}>[]>;
    number?: pulumi.Input<string>;
}

export interface NetworkDhcp {
    enabled?: pulumi.Input<boolean>;
}

export interface NetworkDns {
    enabled?: pulumi.Input<boolean>;
    forwarders?: pulumi.Input<pulumi.Input<inputs.NetworkDnsForwarder>[]>;
    hosts?: pulumi.Input<pulumi.Input<inputs.NetworkDnsHost>[]>;
    localOnly?: pulumi.Input<boolean>;
    srvs?: pulumi.Input<pulumi.Input<inputs.NetworkDnsSrv>[]>;
}

export interface NetworkDnsForwarder {
    address?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
}

export interface NetworkDnsHost {
    hostname?: pulumi.Input<string>;
    ip?: pulumi.Input<string>;
}

export interface NetworkDnsSrv {
    domain?: pulumi.Input<string>;
    port?: pulumi.Input<string>;
    priority?: pulumi.Input<string>;
    protocol?: pulumi.Input<string>;
    service?: pulumi.Input<string>;
    target?: pulumi.Input<string>;
    weight?: pulumi.Input<string>;
}

export interface NetworkDnsmasqOptions {
    options?: pulumi.Input<pulumi.Input<inputs.NetworkDnsmasqOptionsOption>[]>;
}

export interface NetworkDnsmasqOptionsOption {
    optionName?: pulumi.Input<string>;
    optionValue?: pulumi.Input<string>;
}

export interface NetworkRoute {
    cidr: pulumi.Input<string>;
    gateway: pulumi.Input<string>;
}

export interface NetworkXml {
    xslt?: pulumi.Input<string>;
}

export interface PoolSource {
    devices?: pulumi.Input<pulumi.Input<inputs.PoolSourceDevice>[]>;
    name?: pulumi.Input<string>;
}

export interface PoolSourceDevice {
    path?: pulumi.Input<string>;
}

export interface PoolTarget {
    path?: pulumi.Input<string>;
}

export interface PoolXml {
    xslt?: pulumi.Input<string>;
}

export interface VolumeXml {
    xslt?: pulumi.Input<string>;
}
