// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DomainBootDevice {
    devs?: string[];
}

export interface DomainConsole {
    sourceHost?: string;
    sourcePath?: string;
    sourceService?: string;
    targetPort: string;
    targetType?: string;
    type: string;
}

export interface DomainCpu {
    mode: string;
}

export interface DomainDisk {
    blockDevice?: string;
    file?: string;
    scsi?: boolean;
    url?: string;
    volumeId?: string;
    wwn: string;
}

export interface DomainFilesystem {
    accessmode?: string;
    readonly?: boolean;
    source: string;
    target: string;
}

export interface DomainGraphics {
    autoport?: boolean;
    listenAddress?: string;
    listenType?: string;
    type?: string;
    websocket?: number;
}

export interface DomainNetworkInterface {
    addresses: string[];
    bridge?: string;
    hostname: string;
    mac: string;
    macvtap?: string;
    networkId: string;
    networkName: string;
    passthrough?: string;
    private?: string;
    vepa?: string;
    waitForLease?: boolean;
}

export interface DomainNvram {
    file: string;
    template: string;
}

export interface DomainTimeouts {
    create?: string;
}

export interface DomainTpm {
    backendDevicePath?: string;
    backendEncryptionSecret?: string;
    backendPersistentState?: boolean;
    backendType?: string;
    backendVersion?: string;
    model?: string;
}

export interface DomainVideo {
    type?: string;
}

export interface DomainXml {
    xslt?: string;
}

export interface GetNodeDeviceInfoCapability {
    address?: string;
    block: string;
    bus: string;
    capability?: {[key: string]: string};
    class: string;
    description: string;
    device: string;
    domain: string;
    driveType: string;
    drmType: string;
    features?: string[];
    firmware?: {[key: string]: string};
    function: string;
    hardware?: {[key: string]: string};
    host: string;
    interface?: string;
    iommuGroup?: outputs.GetNodeDeviceInfoCapabilityIommuGroup;
    link?: {[key: string]: string};
    logicalBlockSize: string;
    lun: string;
    model: string;
    numBlocks: string;
    number: string;
    product?: {[key: string]: string};
    protocol: string;
    scsiType: string;
    serial: string;
    size: string;
    slot: string;
    subclass: string;
    target: string;
    type: string;
    uniqueId: string;
    vendor?: {[key: string]: string};
}

export interface GetNodeDeviceInfoCapabilityIommuGroup {
    addresses: {[key: string]: string}[];
    number: string;
}

export interface GetNodeDeviceInfoDevnode {
    path: string;
    type: string;
}

export interface NetworkDhcp {
    enabled: boolean;
}

export interface NetworkDns {
    enabled?: boolean;
    forwarders?: outputs.NetworkDnsForwarder[];
    hosts?: outputs.NetworkDnsHost[];
    localOnly?: boolean;
    srvs?: outputs.NetworkDnsSrv[];
}

export interface NetworkDnsForwarder {
    address?: string;
    domain?: string;
}

export interface NetworkDnsHost {
    hostname?: string;
    ip?: string;
}

export interface NetworkDnsSrv {
    domain?: string;
    port?: string;
    priority?: string;
    protocol?: string;
    service?: string;
    target?: string;
    weight?: string;
}

export interface NetworkDnsmasqOptions {
    options?: outputs.NetworkDnsmasqOptionsOption[];
}

export interface NetworkDnsmasqOptionsOption {
    optionName?: string;
    optionValue?: string;
}

export interface NetworkRoute {
    cidr: string;
    gateway: string;
}

export interface NetworkXml {
    xslt?: string;
}

export interface PoolSource {
    devices?: outputs.PoolSourceDevice[];
    name?: string;
}

export interface PoolSourceDevice {
    path?: string;
}

export interface PoolTarget {
    path: string;
}

export interface PoolXml {
    xslt?: string;
}

export interface VolumeXml {
    xslt?: string;
}

