# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/53d3ff65-7d76-4291-a0fc-04ae8ffa51eb";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a88b2b3b-7ed7-4138-a6ac-2fb73349afc1";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E033-67D1";
      fsType = "vfat";
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/f73c6aeb-f60c-449a-8bb9-1fbba342a95c";
      fsType = "ext4";
    };

  fileSystems."/home/erik/src" =
    { device = "/dev/disk/by-uuid/2d52f66d-6340-409d-abe3-4688112da9ec";
      fsType = "ext4";
    };

  fileSystems."/home/erik/Games" =
    { device = "/dev/disk/by-uuid/38d92c32-61a2-41c3-89d5-38e466c5aa91";
      fsType = "ext4";
    };

  fileSystems."/home/erik/Downloads" =
    { device = "/dev/disk/by-uuid/53d356ba-1679-4448-97d6-8bf14768f7ad";
      fsType = "ext4";
    };

  fileSystems."/home/erik/Documents" =
    { device = "/dev/disk/by-uuid/2ad80130-7b2a-4958-9fef-6d0db7874b8f";
      fsType = "ext4";
    };

  fileSystems."/home/erik/Videos" =
    { device = "/dev/disk/by-uuid/8d9c33be-e6b8-4112-a7b7-360f4f34a2ed";
      fsType = "ext4";
    };

  fileSystems."/home/erik/.cache" =
    { device = "/dev/disk/by-uuid/2ffef048-218a-4599-ba99-6e2d07162cc7";
      fsType = "ext4";
    };

  fileSystems."/home/erik/Games/Emulators" =
    { device = "/dev/disk/by-uuid/dad27e0b-62dc-46a0-a73d-473e15973b0a";
      fsType = "ext4";
    };

  fileSystems."/home/erik/Games/Steam" =
    { device = "/dev/disk/by-uuid/d845e722-a58f-4101-9dfc-c22bdf67ec44";
      fsType = "ext4";
    };

  fileSystems."/opt/piavpn/etc/cgroup/net_cls" =
    { device = "none";
      fsType = "cgroup";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/59f4c3c7-6833-41cc-8d20-bacc88cbaaa1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-94c991370dad.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth14a53c8.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth594ba61.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethc232a5d.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethcbcf675.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
